project_id = "slmskfdoinjqtuagaoky"

[functions.fetch-gsr-data]
verify_jwt = false

[functions.dashboard-login]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.monthly-refresh]
verify_jwt = false

[functions.get-snapshot]
verify_jwt = false

[functions.refresh-status]
verify_jwt = false
